# Generated by Django 3.0.6 on 2020-10-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'slug')},
        ),
    ]
